model:
  dt: 0.5
  ataus: [10.0, 200.0]
  t_refract: 2.0
  filter:
    rank: 2
    len: 50
    ncos: 12
  prior:
    l1: 585.0558005127248
    l2: 30.792410553301334
data:
  source: "crcns"
  root: "/home/data/crcns"
  cell: "blabla0903_2_B"
  stimulus:
    stim_type: "conspecific"
    spectrogram:
      window: 2.5
      compress: 1
      f_min: 1.0
      f_max: 8.0
      f_count: 20
      gammatone: True
  prepadding: 50.0
  dt: 1.0
  test_proportion: 0.2
spike_detect:
  thresh: -20.0
  rise_dt: 1.0
xvalidate:
  gtol: 0.01
  early_stop: 3
  grid:
    lower: -1
    upper: 5
    count: 20
  l1_ratios: [0.1, 0.5, 0.7, 0.9, 0.95]
emcee:
  nsteps: 500
  nthreads: 8
  nwalkers: 1000
  startpos_scale: 2.0
  bounds:
  - [0, 20]
  - [-50, 200]
  - [-5, 10]
