model:
  dt: 0.5
  ataus: [10.0, 200.0]
  t_refract: 2.0
  filter:
    rank: 2
    len: 30
    ncos: 8
  prior:
    l1: 0.0
    l2: 0.0
data:
  stimulus:
    source: "randn"
    duration: 400000
  model: "multivariate_glm"
  filter:
    fn: "gabor"
    nfreq: 14
    ntau: 30
    f_max: 8000
    f_peak: 4000
    t_peak: 12
    ampl: -1
    t_sigma: 6
    f_sigma: 2400
    theta: 0
    lmbda: 19
    psi: 1.5
  adaptation: [7.0, 100.0, 2.0]
  trial_noise:
    snr: 2.0
  random_seed: 1
  dt: 10.0
  trials: 5
xvalidate:
  grid:
    lower: -1
    upper: 5
    count: 20
  l1_ratios: [0.1, 0.5, 0.7, 0.9, 0.95]
emcee:
  nsteps: 200
  nthreads: 8
  nwalkers: 1000
  startpos_scale: 2.0
mat:
  bounds:
  - [0, 20]
  - [-50, 200]
  - [-5, 10]
