model:
  dt: 0.5
  ataus: [10.0, 200.0]
  t_refract: 2.0
  filter:
    rank: 2
    len: 30
    ncos: 8
data:
  stimulus:
    source: "randn"
    duration: 400000
  model: "multivariate_glm"
  filter:
    fn: "gabor"
    nfreq: 14
    ntau: 30
    f_max: 8000
    f_peak: 4000
    t_peak: 12
    ampl: -1
    t_sigma: 6
    f_sigma: 2400
    theta: 0
    lmbda: 19
    psi: 1.5
  adaptation: [7.0, 100.0, 2.0]
  trial_noise:
    sd: 2.0
  random_seed: 1
  dt: 10.0
  trials: 1
spike_detect:
  thresh: -20.0
  rise_dt: 1.0
emcee:
  nsteps: 20
  nthreads: 8
  nwalkers: 100
  startpos_scale: 2.0
mat:
  bounds:
  - [0, 20]
  - [-50, 200]
  - [-5, 10]
  model_dt: 0.5
  nlin: exp
  refract: 2.0
