model:
  dt: 0.5
  ataus: [10.0, 200.0]
  t_refract: 2.0
  filter:
    rank: 2
    len: 50
    ncos: 12
  prior:
    l1: 50
    l2: 5
data:
  stimulus:
    source: "crcns"
    root: "crcns"
    spectrogram:
      window: 2.5
      compress: 10
      f_min: 0
      f_max: 8.0
      f_count: 20
      gammatone: False
  model: "multivariate_dynamical"
  dynamics:
    model: "models/tonic.yml"
    current_scaling: 1.0
  filter:
    fn: "hg_dstrf"
    paramfile: "config/hg_filters.csv"
    rf: 24
    nfreq: 20
    ntau: 50
    t_max: 50
    ampl: 1.5
    f_max: 8
    Pf: 0.0
  trial_noise:
    color: pink
    snr: 2.0
  random_seed: 1
  dt: 1.0
  trials: 10
  test_proportion: 0.2
spike_detect:
  thresh: -20.0
  rise_dt: 1.0
xvalidate:
  grid:
    lower: -1
    upper: 5
    count: 20
  l1_ratios: [0.1, 0.5, 0.7, 0.9, 0.95]
emcee:
  nsteps: 500
  nthreads: 8
  nwalkers: 1000
  startpos_scale: 2.0
  bounds:
  - [0, 20]
  - [-50, 200]
  - [-5, 10]
