model:
  dt: 0.5
  ataus: [10.0, 200.0]
  t_refract: 2.0
  filter:
    rank: 2
    len: 50
    ncos: 12
  prior:
    l1: 10.0
    l2: 10.0
data:
  stimulus:
    source: "crcns"
    root: "crcns"
    spectrogram:
      window: 2.5
      compress: 10
      f_min: 0.0
      f_max: 8.0
      f_count: 20
      gammatone: False
  model: "multivariate_glm"
  filter:
    fn: "hg"
    nfreq: 20
    ntau: 50
    t_max: 50
    ampl: 1.0
    f_max: 8000
    f_peak: 2844
    f_sigma: 1504
    f_omega: 0.0001329
    t_peak: 8.19517332914
    t_sigma: 4.3656196941
    t_omega: 0.04398
    Pt: 1.571
    Pf: 0.0
  adaptation: [7.0, 100.0, 2.0]
  trial_noise:
    snr: 4.0
    random_seed: 1
  dt: 1.0
  trials: 10
  test_proportion: 0.2
xvalidate:
  grid:
    lower: -1
    upper: 5
    count: 20
  l1_ratios: [0.1, 0.5, 0.7, 0.9, 0.95]
emcee:
  nsteps: 200
  nthreads: 8
  nwalkers: 1000
  startpos_scale: 2.0
  bounds:
  - [0, 20]
  - [-50, 200]
  - [-5, 10]
