model:
  dt: 0.5
  ataus: [10.0, 200.0]
  t_refract: 2.0
  filter:
    rank: 2
    len: 50
    ncos: 12
  prior:
    l1: 585.0558005127248
    l2: 30.792410553301334
data:
  source: "neurobank"
  cell: ""
  stimulus:
    include:
      - A0
      - A0_motifs_000
      - A0_motifs_001
      - A0_motifs_002
      - A0_motifs_003
      - A1
      - A2
      - A2_motifs_000
      - A3
      - A4
      - A5
      - A6_motifs_000
      - A8
      - A8_motifs_000
      - A8_motifs_001
      - A8_motifs_002
      - A8_motifs_003
      - A9
      - B0
      - B0_motifs_000
      - B0_motifs_001
      - B0_motifs_002
      - B0_motifs_003
      - B1
      - B2
      - B2_motifs_000
      - B3
      - B4
      - B5
      - B6_motifs_000
      - B8
      - B8_motifs_000
      - B8_motifs_001
      - B8_motifs_002
      - B8_motifs_003
      - B9
      - C0
      - C0_motifs_000
      - C0_motifs_001
      - C0_motifs_002
      - C0_motifs_003
      - C1
      - C2
      - C2_motifs_000
      - C6_motifs_000
      - C8_motifs_000
      - C8_motifs_001
      - C8_motifs_002
      - C8_motifs_003
    spectrogram:
      window: 2.5
      compress: 1
      f_min: 0.3
      f_max: 10.0
      f_count: 24
      gammatone: True
  prepadding: 50.0
  dt: 1.0
  test:
    trials: 50
spike_detect:
  thresh: -20.0
  rise_dt: 1.0
xvalidate:
  gtol: 0.01
  early_stop: 3
  grid:
    lower: -1
    upper: 5
    count: 20
  l1_ratios: [0.1, 0.5, 0.7, 0.9, 0.95]
emcee:
  nsteps: 500
  nthreads: 8
  nwalkers: 1000
  startpos_scale: 2.0
  bounds:
  - [0, 20]
  - [-50, 200]
  - [-5, 10]
