model:
  dt: 0.5
  ataus: [10.0, 200.0]
  t_refract: 2.0
  filter:
    len: 60
    ncos: 8
data:
  stimulus:
    source: "randn"
    duration: 100000
  filter:
    fn: "gammadiff"
    tau1: 32.0
    tau2: 16.0
    amplitude: 10.0
    ntau: 60
    dt: 10.0
  model: "multivariate_dynamical"
  dynamics:
    model: "models/pospischil_sm.yml"
    current_scaling: 2.0
  trial_noise:
    sd: 2.0
  random_seed: 1
  dt: 10.0
  trials: 10
spike_detect:
  thresh: -20.0
  rise_dt: 1.0
regularization:
  lmbda: 0
  alpha: 1.0
emcee:
  nsteps: 200
  nthreads: 8
  nwalkers: 500
  startpos_scale: 2.0
mat:
  bounds:
  - [0, 20]
  - [-50, 200]
  - [-5, 10]
  model_dt: 0.5
  nlin: exp
  refract: 2.0
  taus: [10.0, 200.0]
