model:
  dt: 0.5
  ataus: [10.0, 200.0]
  t_refract: 2.0
  filter:
    len: 60
    ncos: 8
  prior:
    l1: 1.0
    l2: 0.0
data:
  source: "randn"
  stimulus:
    duration: 100000
    random_seed: 1048
  filter:
    fn: "gammadiff"
    tau1: 32.0
    tau2: 16.0
    amplitude: 10.0
    ntau: 60
    dt: 10.0
  model: "multivariate_dynamical"
  dynamics:
    model: "models/phasic.yml"
    current_scaling: 2.0
  trial_noise:
    snr: 2.0
    random_seed: 1
  dt: 10.0
  trials: 10
spike_detect:
  thresh: -20.0
  rise_dt: 1.0
xvalidate:
  gtol: 0.01
  early_stop: 3
  grid:
    lower: -1
    upper: 5
    count: 20
  l1_ratios: [0.1, 0.5, 0.7, 0.9, 0.95]
emcee:
  nburnin: 5000
  nsteps: 1000
  nthreads: 8
  nwalkers: 1000
  startpos_scale: 0.001
  bounds:
  - [0, 20]
  - [-50, 200]
  - [-5, 10]
