model:
  dt: 0.5
  ataus: [10.0, 200.0]
  filter:
    len: 60
    taus: [32.0, 16.0],
    amplitude: 5.0
  dynamics:
    model: "models/pospischil_sm.yml"
    current_scaling: 2.0
stim:
  dt: 10.0
  duration: 100000
spike_detect:
  thresh: -20.0
  rise_dt: 1.0
emcee:
  nsteps: 2000
  nthreads: 8
  nwalkers: 500
  startpos_scale: 1.0
mat:
  bounds:
  - [0, 20]
  - [-50, 200]
  - [-5, 10]
  model_dt: 0.5
  nlin: exp
  refract: 2.0
  taus: [10.0, 200.0]
