model:
  dt: 0.5
  ataus: [10.0, 200.0]
  t_refract: 2.0
  filter:
    len: 60
    ncos: 8
  prior:
    l1: 0.0
    l2: 0.0
data:
  stimulus:
    source: "randn"
    duration: 400000
    intro: 100
  filter:
    fn: "gammadiff"
    tau1: 32.0
    tau2: 16.0
    amplitude: 10.0
    ntau: 60
    dt: 10.0
  model: "multivariate_glm"
  adaptation: [7.0, 100.0, 2.0]
  trial_noise:
    sd: 2.0
  random_seed: 1
  dt: 10.0
  trials: 5
emcee:
  nsteps: 200
  nthreads: 8
  nwalkers: 500
  startpos_scale: 2.0
mat:
  bounds:
  - [0, 20]
  - [-50, 200]
  - [-5, 10]
  model_dt: 0.5
  nlin: exp
  refract: 2.0
